analyzer:
  errors:
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
