name: cinequest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  ## Localization & Date Format
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.7

  # Api
  retrofit: ^4.1.0
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  logger: any # for logging purposes

  # Services
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  get_storage: ^2.1.1
  flutter_secure_storage: ^4.2.1
  sqflite: ^2.3.3+1

  # Push Nitification
  # awesome_notifications: ^0.9.3

  # Annotation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Image
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

  # Navigation
  go_router: ^14.2.7

  # Statement
  flutter_bloc: ^8.1.6

  # Other
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.5
  page_transition: ^2.1.0
  rxdart: ^0.28.0
  envied: ^0.5.4+1
  dartz: ^0.10.1
  get_it: ^7.7.0
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  uuid: ^4.5.0
  path_provider: ^2.1.4
  carousel_slider: ^5.0.0
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  retrofit_generator: ^9.1.2
  flutter_gen_runner: ^5.7.0
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  envied_generator: ^0.5.4+1
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/colors/

  fonts:
    - family: SI
      fonts:
        - asset: assets/fonts/si/SuisseIntl-Light.ttf
          weight: 300
        - asset: assets/fonts/si/SuisseIntl-Medium.ttf
          weight: 400
        - asset: assets/fonts/si/SuisseIntl-Regular.ttf
          weight: 500

flutter_intl:
  enabled: true
  arb_dir: assets/languages/
  output_dir: lib/src/core/localization
  main_locale: en

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

  assets:
    enabled: true

    outputs:
      class_name: AppAssets
      package_parameter_enabled: false

  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/color.xml
